### PR TITLE
Fixes to issues #51 and #44

### PR DESCRIPTION
**Pull request by temiyemi**
Some refactoring of script.js; pruning of assets to remove all unused files; and some more enhancements

### CODE REVIEW

**Comment by temiyemi** [comment]
Sure.

**Comment by temiyemi** [comment]
No p. Will do.

**Comment by temiyemi** [comment]
Done.

**Comment by temiyemi** [comment]
Check again @dadepo I just made some changes

**Comment by dadepo** [comment]
Merged. Thanks once again!

**Pull request merged**
